name: python build

on: 
push: 
   branches:
     - main
workflow_dispatch:

jobs:
  pybldjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildstep2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
