name: python build

on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  pybldjob1:
    runs-on: leelintst01
    steps:
      - name: run as root
      - run: sudo su -
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildstep2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: pybuildstep3
        run: pytest
        continue-on-error: true
      - name: checking error
        run: echo testing after error execution
      - name: installing docker package
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: creating docker image
        run: |
          set -x 
          docker version
          docker build -t leebonstephen/pydock2 .
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_NAME }} 
          password: ${{ secrets.USER_PASSWD }}
      - name: docker push
        run: |
          docker push leebonstephen/pydock2
